#!/usr/bin/env bash

core=STMicroelectronics:stm32
# list boards with 'arduino-cli board listall'
board=GenL5
# list board options with 'arduino-cli board details -b STMicroelectronics:stm32:board'
board_options=upload_method=swdMethod,pnum=GENERIC_L552ZETXQ

function setup {
    arduino-cli core install ${core} \
        --additional-urls https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json
}

function compile {
   arduino-cli compile . -b ${core}:${board} \
        --board-options ${board_options}
}

function upload {
    compile
    arduino-cli upload . -b ${core}:${board} \
        --board-options ${board_options}
}

function monitor {
    arduino-cli monitor -p /dev/ttyACM0 -c baudrate=115200
}

function details {
    arduino-cli board details -b ${core}:${board}
}

# easily run subcommands.  e.g. "./build upload"
"$@"
